server:
  port: 8090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/arodriguezcu/proyecto01-tutoriales.git
          searchPaths: config-data
          default-label: main
          username: ${GIT_USER}
          password: ${GIT_PASSWORD}
                              
  security:
    user:
      name: root
      password: 123